# Generated by Django 4.1.5 on 2023-01-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitacion', '0016_alter_tipohabitacion_options_habitacion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField(blank=True, help_text='MM/DA/AAAA', null=True, verbose_name='Check_in')),
                ('check_out', models.DateField(blank=True, help_text='MM/DA/AAAA', null=True, verbose_name='Check_out')),
                ('cantNoches', models.IntegerField(verbose_name='Cantidad Noches')),
                ('Habitacion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion', verbose_name='Habitación')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaIngreso', models.DateField(auto_now_add=True, help_text='MM/DA/AAAA', null=True, verbose_name='Fecha de Ingreso')),
                ('cantidadHabitaciones', models.PositiveIntegerField(default=1, verbose_name='Cantidad o Stock')),
                ('numeroHuespedes', models.IntegerField(verbose_name='Numero de Huéspedes')),
                ('valorReserva', models.BigIntegerField(verbose_name='Valor Reserva')),
                ('Check_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.check', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Habitacion_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion', verbose_name='Habitación')),
                ('Reserva_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva', verbose_name='Reserva')),
            ],
        ),
    ]
