# Generated by Django 4.1.5 on 2023-01-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaIngreso', models.DateField(auto_now_add=True, help_text='MM/DA/AAAA', null=True, verbose_name='Fecha de Ingreso')),
                ('nombres', models.CharField(blank=True, max_length=45, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=50, verbose_name='Apellidos')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Correo Electronico')),
                ('asunto', models.CharField(max_length=45, verbose_name='Asunto')),
                ('comentarioCliente', models.CharField(max_length=250, verbose_name='Comentario')),
                ('adjunto', models.CharField(max_length=250, verbose_name='Adjunto')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
