# Generated by Django 4.1.5 on 2023-01-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqrs',
            options={'verbose_name': 'PQRS', 'verbose_name_plural': 'PQRS'},
        ),
        migrations.AddField(
            model_name='pqrs',
            name='numeroDocumento',
            field=models.IntegerField(null=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='pqrs',
            name='tipoDocumento',
            field=models.CharField(choices=[('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Cédula de Extranjería', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte')], default='Cédula de Ciudadanía', max_length=25, verbose_name='Tipo de Documento'),
        ),
    ]
