# Generated by Django 4.1.5 on 2023-01-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_alter_pqrs_options_pqrs_numerodocumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='apellidos',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='nombres',
            field=models.CharField(max_length=45, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='telefono',
            field=models.CharField(max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
