# Generated by Django 4.1.5 on 2023-01-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0003_alter_pqrs_apellidos_alter_pqrs_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='adjunto',
            field=models.FileField(upload_to='', verbose_name='Adjuntar Archivo'),
        ),
    ]
