# Generated by Django 4.1.5 on 2023-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0004_alter_pqrs_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='asunto',
            field=models.CharField(choices=[('Petición', 'Petición'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Solicitud', 'Solicitud'), ('Denuncia', 'Denuncia'), ('Reembolso', 'Reembolso'), ('Estafa', 'Estafa'), ('Robo', 'Robo')], default='Petición', max_length=45, verbose_name='Asunto'),
        ),
    ]
