# Generated by Django 4.1.5 on 2023-01-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroHabitacion', models.CharField(max_length=4, verbose_name='Numero de Habitacion')),
                ('disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada')], default='Disponible', max_length=10, verbose_name='Disponibilidad')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreHabitacion', models.CharField(choices=[('Sencilla', 'Sencilla'), ('Doble', 'Doble'), ('Campestre', 'Campestre'), ('Individual', 'Individual'), ('Doble King', 'Doble King'), ('Cabaña Alpina', 'Cabaña Alpina')], max_length=45, null=True, verbose_name='Nombre Habitacion')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion Habitacion')),
                ('capacidad', models.CharField(max_length=45, verbose_name='Capacidad')),
                ('valor', models.IntegerField(verbose_name='Valor Habitacion')),
                ('sede', models.CharField(choices=[('estacion', 'La Estación'), ('bosque', 'El Bosque')], default='estacion', max_length=8, verbose_name='Sede')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad o Stock')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
        ),
    ]
