# Generated by Django 4.1.5 on 2023-01-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.BooleanField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numeroHabitacion',
            field=models.IntegerField(verbose_name='Numero de Habitacion'),
        ),
    ]
