# Generated by Django 4.1.5 on 2023-01-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0003_alter_tipohabitacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipohabitacion',
            name='sede',
            field=models.CharField(choices=[('estacion', 'La Estación'), ('bosque', 'El Bosque')], max_length=8, verbose_name='Sede'),
        ),
    ]
