# Generated by Django 4.1.5 on 2023-01-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0004_alter_tipohabitacion_sede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'verbose_name': 'Habitacion', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipohabitacion',
            options={'verbose_name': 'TipoHabitacion', 'verbose_name_plural': 'TipoHabitaciones'},
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.BooleanField(choices=[('1', '1'), ('0', '0')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
