# Generated by Django 4.1.5 on 2023-01-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0005_alter_habitacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
