# Generated by Django 4.1.5 on 2023-01-26 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0007_alter_habitacion_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tipohabitacion',
            name='sede',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='TipoHabitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habitacion.tipohabitacion', verbose_name='Tipo de Habitación'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='sede',
            field=models.CharField(blank=True, choices=[('estacion', 'La Estación'), ('bosque', 'El Bosque')], max_length=8, null=True, verbose_name='Sede'),
        ),
    ]
