# Generated by Django 4.1.5 on 2023-01-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0008_remove_habitacion_estado_remove_tipohabitacion_sede_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='sede',
            field=models.CharField(choices=[('estacion', 'La Estación'), ('bosque', 'El Bosque')], max_length=8, null=True, verbose_name='Sede'),
        ),
    ]
