# Generated by Django 4.1.5 on 2023-01-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0009_alter_habitacion_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='sede',
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='sede',
            field=models.CharField(choices=[('estacion', 'La Estación'), ('bosque', 'El Bosque')], max_length=8, null=True, verbose_name='Sede'),
        ),
    ]
