# Generated by Django 4.1.5 on 2023-01-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0011_remove_tipohabitacion_sede_habitacion_sede'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='TipoHabitacion',
            new_name='TipoHabitacion_id',
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='nombreHabitacion',
            field=models.CharField(choices=[('Sencilla', 'Sencilla'), ('Doble', 'Doble'), ('Campestre', 'Campestre'), ('Individual', 'Individual'), ('Doble King', 'Doble King'), ('Cabaña Alpina', 'Cabaña Alpina')], max_length=45, null=True, verbose_name='Nombre de Habitación'),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='valor',
            field=models.IntegerField(verbose_name='Valor'),
        ),
    ]
