# Generated by Django 4.1.5 on 2023-01-26 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0012_rename_tipohabitacion_habitacion_tipohabitacion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='TipoHabitacion_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habitacion.tipohabitacion', verbose_name='Tipo de Habitación'),
        ),
    ]
