# Generated by Django 4.1.5 on 2023-01-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0014_rename_tipohabitacion_id_habitacion_tipohabitacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitacion',
            old_name='TipoHabitacion',
            new_name='TipoHabitacion_id',
        ),
    ]
