# Generated by Django 4.1.5 on 2023-01-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0015_rename_tipohabitacion_habitacion_tipohabitacion_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipohabitacion',
            options={'ordering': ['nombreHabitacion'], 'verbose_name': 'TipoHabitacion', 'verbose_name_plural': 'TipoHabitaciones'},
        ),
        migrations.AddField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
    ]
